version: "3.8"

services:
  setpointer:
    build:
      context: ./
      dockerfile: ./price_driven_switch/dockerfile
    container_name: setpoint-app
    restart: always
    volumes:
      - setpoint-config:/app/price_driven_switch/config
    environment:
      - PYTHONUNBUFFERED=1
      - TZ=Europe/Oslo
    ports:
      - "8080:8080"
      - "8501:8501"

  nginx:
    build: ./nginx
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    depends_on:
      - setpointer

volumes:
  setpoint-config:
