services:
  setpointer:
    image: pavelapekhtin/price-driven-switch:latest
    container_name: setpoint-app
    restart: always
    volumes:
      - setpoint-config:/app/price_driven_switch/config
    environment:
      - PYTHONUNBUFFERED=1
      - TZ=Europe/Oslo
    ports:
      - "8080:8080"
      - "8501:8501"

  nginx:
    image: pavelapekhtin/nginx-for-price-driven-switch:0.3.4
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    depends_on:
      - setpointer

volumes:
  setpoint-config:


networks:
  custom_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.25.0.1/16
          gateway: 172.18.0.1
