version: "3.8"

services:
  setpointer:
    image: pavelapekhtin/price-driven-switch:latest
    container_name: setpoint-app
    restart: always
    volumes:
      - setpoint-env:/app/.env
      - setpoint-config:/app/price_driven_switch/config
    environment:
      - PYTHONUNBUFFERED=1
      - TZ=Europe/Oslo
    ports:
      - "8080:8080"
      - "8501:8501"

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - setpoint-config:/etc/nginx/conf.d
    depends_on:
      - setpointer

volumes:
  setpoint-env:
  setpoint-config:
