version: "3.8"

services:

  setpointer:
    image: pavelapekhtin/price-driven-switch:latest
    container_name: setpoint-app
    restart: always
    volumes:
      - .env:/.env
      - ./price_driven_switch/config/setpoints.toml:/app/price_driven_switch/config/setpoints.toml
    environment:
      - PYTHONUNBUFFERED=1
      - TZ=Europe/Oslo
    ports:
      - "8080:8080" # For FastAPI
      - "8501:8501" # For Streamlit

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/ngnix.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - setpointer
