version: "3.7"

services:

  setpointer:
    build:
      context: ./
      dockerfile: ./price_driven_switch/dockerfile
    container_name: setpoint-app
    restart: always
    environment:
      - PYTHONUNBUFFERED=1
      - TZ=Europe/Oslo
    ports:
      - "8080:8080" # For FastAPI
      - "8501:8501" # For Streamlit

  nginx:
    build: ./nginx
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    depends_on:
      - setpointer
