[tool.poetry]
name = "price-driven-switch"
version = "3.3.3"
description = "Provide on/off states via GET request based on power price from Tibber API"
authors = ["pavelapekhtin <pavel.apekhtin@gmail.com>"]
license = "MIT"
readme = "README.md"
packages = [{ include = "price_driven_switch", from = "." }]

[tool.poetry.dependencies]
python = ">=3.10,<4.0"
asyncio = "^3.4.3"
python-graphql-client = "^0.4.3"
uvicorn = "^0.23.2"
python-dotenv = "^1.0.0"
watchdog = "^3.0.0"
toml = "^0.10.2"
pytibber = "^0.28.2"
icecream = "^2.1.3"
loguru = "^0.7.2"
types-requests = "^2.31.0.8"
plotly = "^5.14.1"
pandas = "^2.1.0"
streamlit = "^1.22.0"
fastapi = "^0.109.2"

[tool.poetry.group.dev.dependencies]
pytest = "^7.3.1"
pylint = "^2.17.3"
pytest-cov = "^4.0.0"
freezegun = "^1.2.2"
commitizen = "^3.7.0"
mypy = "^1.5.1"
types-toml = "^0.10.8.7"
pandas-stubs = "^2.0.3.230814"
black = "^24.4.2"
ipykernel = "^6.25.2"
hypothesis = "^6.86.2"
pytest-asyncio = "^0.21.1"
httpx = "^0.25.0"

[tool.mypy]
exclude = "^tests/.*"

[tool.commitizen]
name = "cz_conventional_commits"
tag_format = "$version"
version_scheme = "pep440"
version_provider = "poetry"
update_changelog_on_bump = true
major_version_zero = false

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
