[tool.poetry]
name = "price-driven-switch"
version = "0.4.4"
description = "Provide on/off states via GET request based on power price from Tibber API"
authors = ["pavelapekhtin <pavel.apekhtin@gmail.com>"]
license = "MIT"
readme = "README.md"
packages = [{ include = "price_driven_switch", from = "." }]

[tool.poetry.dependencies]
python = ">=3.9,<3.9.7 || >3.9.7,<3.12"
asyncio = "^3.4.3"
python-graphql-client = "^0.4.3"
fastapi = "^0.103.0"
uvicorn = "^0.23.2"
python-dotenv = "^1.0.0"
watchdog = "^3.0.0"
toml = "^0.10.2"

[tool.poetry.group.frontend.dependencies]
plotly = "^5.14.1"
pandas = "^2.1.0"
streamlit = "^1.22.0"

[tool.poetry.group.dev.dependencies]
pytest = "^7.3.1"
pylint = "^2.17.3"
pytest-cov = "^4.0.0"
freezegun = "^1.2.2"
commitizen = "^3.7.0"
mypy = "^1.5.1"
types-toml = "^0.10.8.7"
pandas-stubs = "^2.0.3.230814"
black = "^23.7.0"

[tool.mypy]
exclude = "^tests/.*"

[tool.commitizen]
name = "cz_conventional_commits"
tag_format = "$version"
version_scheme = "pep440"
version_provider = "poetry"
update_changelog_on_bump = true
major_version_zero = true

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
