name: Test and Publish

on:
  push:
    branches:
      - main  
    tags:
      - '*'

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Tox and Poetry
      run: |
        pip install tox
        pip install poetry
    - name: Install Dependencies
      run: poetry install
    - name: Run Tox
      run: tox 

  docker-build-push:
    needs: test
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Extract tag name
      shell: bash
      run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_KEY }}
    - name: Build and push Docker for Setpoint App
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        platforms: linux/amd64,linux/arm64
        tags: |
          pavelapekhtin/price-driven-switch:${{ env.VERSION }}
          pavelapekhtin/price-driven-switch:latest
        file: ./price_driven_switch/Dockerfile

  docker-build-push-nginx:
    needs: docker-build-push
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Extract tag name
      shell: bash
      run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_KEY }}
    - name: Build and push Docker for Custom Nginx
      uses: docker/build-push-action@v4
      with:
        context: ./nginx
        push: true
        platforms: linux/amd64,linux/arm64
        tags: |
          pavelapekhtin/nginx-for-price-driven-switch:${{ env.VERSION }}
          pavelapekhtin/nginx-for-price-driven-switch:latest
        file: ./nginx/Dockerfile
